# site and SEO
title: npb.space
author: Nic Becker
baseurl: ""
url: "https://npb.space"
g_analytics:
logo: "/assets/imgs/apple-touch-icon.png"

# bio
header: npb.space
desc: >
  I'm Nic Becker, an undergraduate in Philosophy and Physics at Stanford. My interests
  are a bit all over the place. Currently, I'm working in Shaul Druckmann's computational
  neuroscience group. Here you'll find some more info about me, my project blog, and
  miscellaneous notes. You can get in touch with me at npbecker [at] stanford [dot] edu

# posts
date_format: "%Y"
post_title: Title
post_date: Year
post_cat: Type

# post detail
prev-next: true

# build settings
markdown: kramdown
#theme: louie
exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-seo-tag
